from app.backend.llm.groq import GroqLLM
from langchain_core.messages import HumanMessage


def greet(state):
    """
    Greet the user and/or explain what you can do.

    Args:
        state (messages): The current state
        
    Returns:
        dict: The updated state with greetings
    """

    print("---GREET---")
    messages = state["messages"]
    question = state['question']

    msg = [
        HumanMessage(
            content=f"""
    You are BONsAI, a helpful assistant for GEO BON members. \
    GEO BON (Group on Earth Observations Biodiversity Observation Network) \
    is a global network of researchers dedicated to improving \
    the acquisition, coordination, and delivery of biodiversity information at the global, regional, and national levels.

    ### What to do:
    - **Greet users if and only if** they greet you or ask how you're doing.
    - **Always explain BONsAI's purpose** and offer them to help.
    - **Do not answer other types of questions** — your job here is just to introduce BONsAI and respond to greetings.

    ### What BONsAI Can Do:
    BONsAI helps users answer questions based **only** on the following resources:
    1. [GEO BON Scientific Publications](https://geobon.org/documents/scientific-publications/)
    2. [BON in a Box Tools Catalogue](https://boninabox.geobon.org/tools)
    3. [BON in a Box Pipelines GitHub](https://github.com/GEO-BON/bon-in-a-box-pipelines)
    4. [BON in a Box Pipeline Engine GitHub](https://github.com/GEO-BON/bon-in-a-box-pipeline-engine)

    If asked, explain this clearly and include links. Do **not** make up information or answer unrelated queries.

    ---

    User's input:
    {question}

    ---

    Your response:
    """
        )
    ]

    manual_greet = [
        HumanMessage(
            content=f"""
    ## ❗ Sorry, I couldn't answer your question

    🌍 I'm BONsAI – the assistant for GEO BON members.  

    I'm here to help you find answers using the resources listed below. Let's make exploring biodiversity knowledge easier!

    ---

    ### 📚 What BONsAI Can Do:
    I assist you in answering questions based on the following GEO BON resources:
    1. [GEO BON Scientific Publications](https://geobon.org/documents/scientific-publications/)
    2. [BON in a Box Tools Catalogue](https://boninabox.geobon.org/tools)
    3. [BON in a Box Pipelines GitHub](https://github.com/GEO-BON/bon-in-a-box-pipelines)
    4. [BON in a Box Pipeline Engine GitHub](https://github.com/GEO-BON/bon-in-a-box-pipeline-engine)

    ---

    ### ❓ Why I Couldn't Answer:
    It seems I couldn't retrieve information relevant to your query. This could be because:
    - The question isn't related to the resources I have access to. Please remember that I can only assist with the sources listed above.
    - I couldn't retrieve the information even though it should be available. You might want to try rewording your query. If you think the information should have been found, please provide feedback by clicking the thumbs down button – your input helps us improve!

    ---

    ### 👍👎 Feedback:
    If you would like to give feedback on my response, you can use the **thumbs up (👍)** or **thumbs down (👎)** buttons. If you choose the thumbs down, you will have the option to add an additional comment. Your feedback helps us improve.

    ---

    ### 🔒 Your Privacy Matters:
    Your chat with me is **not shared or recorded** unless you choose to provide feedback using the thumbs up or down buttons. If you do, only the messages in this interaction will be recorded for improvement purposes.

    ---
    
    🌱 **Sustainability Note:** This message was crafted manually rather than being generated by a Large Language Model. This helps reduce energy consumption and minimizes environmental impact.

    ---

    💬 Let me know what's on your mind, or if you have any questions I can help with!
    """
        )
    ]


    # Greeter
    #rewrite_model = GroqLLM.load_llm()
    #response = rewrite_model.invoke(msg)
    
    return {"messages": manual_greet}

